### ISSUE TITLE
Deprecate item-release

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-deprecated/item-release#117]
Requires https://github.com/sul-dlss/common-accessioning/pull/138

**Comment by aaron-collier** [comment]
@mjgiarlo I believe so, yes.

**Comment by aaron-collier** [comment]
@mjgiarlo now that this is in sul-dlss-deprecated, can this be closed?

**Comment by mjgiarlo** [comment]
@aaron-collier Yup!
