### ISSUE TITLE
release-members for some collection items failing

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss-deprecated/item-release#99]
Example: https://argo.stanford.edu/view/druid:yf563kp2275

release-members : Failed to open TCP connection to sul-dor-prod.stanford.edu:443 (getaddrinfo: Temporary failure in name resolution)

**Comment by blalbrit** [comment]
Continuing to confirm this problem - druid:hf171mk6155 now joins the list of released collections failing this step. This does appear to be a bug.

**Comment by hannahfrost** [comment]
This bug is resurfacing now, in this case here: https://argo.stanford.edu/view/druid:yp581yt0894

**Comment by hannahfrost** [comment]
This ticket is resolved (via #274), but I'm not able to close it. @blalbrit Can you do the honors, please?

**Comment by blalbrit** [comment]
Nice job all!
